"""LangGraph middleware for injecting knowledge-base context."""

from __future__ import annotations

from collections.abc import Sequence
from logging import Logger
from typing import Any

from langchain.agents.middleware import before_agent
from langchain.messages import HumanMessage, SystemMessage
from langchain_core.language_models.chat_models import BaseChatModel
from langchain_core.prompts import ChatPromptTemplate
from langchain_core.runnables import RunnableConfig
from langfuse import observe, propagate_attributes
from pydantic import BaseModel, Field, ValidationError

from app.models.answer import AnswerCandidate
from app.utils.logging import getLogger

logger: Logger = getLogger("zammad-ai.answer.middleware")

KB_CONTEXT_HEADER = "Knowledge-base context"
KB_CONTEXT_EMPTY = "No relevant knowledge-base documents were found for this request."


class KnowledgebaseQuery(BaseModel):
    """Structured search query generated by the LLM."""

    query: str = Field(min_length=1, max_length=200)


def _latest_user_message(messages: Sequence[Any]) -> str:
    for message in reversed(messages):
        if isinstance(message, HumanMessage):
            content = message.content
            if isinstance(content, str) and content.strip():
                return content.strip()
    if not messages:
        return ""
    message = messages[-1]
    content = getattr(message, "content", "")
    return content.strip() if isinstance(content, str) else str(content).strip()


async def _generate_query(query_model: BaseChatModel, messages: Sequence[Any]) -> str:
    prompt = [
        SystemMessage(
            content=(
                "You write concise search queries for a municipal knowledge base. "
                "Return only the most relevant German search terms. Keep the query short."
            )
        ),
        HumanMessage(
            content="Generate a search query for the knowledge base from this user request:\n"
            + _latest_user_message(messages)
        ),
    ]

    structured_model = query_model.with_structured_output(KnowledgebaseQuery)
    result = await structured_model.ainvoke(prompt)

    if isinstance(result, KnowledgebaseQuery):
        return result.query.strip()

    if isinstance(result, dict):
        query = result.get("query", "")
        if isinstance(query, str):
            try:
                return KnowledgebaseQuery.model_validate({"query": query}).query.strip()
            except ValidationError:
                return ""

    query = getattr(result, "query", "")
    if isinstance(query, str):
        try:
            return KnowledgebaseQuery.model_validate({"query": query}).query.strip()
        except ValidationError:
            return ""

    return ""


async def _build_kb_context(runtime: Any, query_model: BaseChatModel, messages: Sequence[Any]) -> str:
    query = await _generate_query(query_model, messages)
    if not query:
        query = _latest_user_message(messages)

    if not query:
        return KB_CONTEXT_HEADER + "\n\n" + KB_CONTEXT_EMPTY

    try:
        query = KnowledgebaseQuery.model_validate({"query": query}).query.strip()
    except ValidationError:
        return KB_CONTEXT_HEADER + "\n\n" + KB_CONTEXT_EMPTY

    qdrant_client = runtime.context.qdrant_kb_client
    documents_with_scores = await qdrant_client.asearch_documents(query=query)

    if not documents_with_scores:
        return KB_CONTEXT_HEADER + "\n\n" + KB_CONTEXT_EMPTY

    sections: list[str] = [KB_CONTEXT_HEADER, "Search query: " + query, ""]
    for index, (document, score) in enumerate(documents_with_scores, start=1):
        metadata = getattr(document, "metadata", {}) or {}
        title = str(metadata.get("title") or metadata.get("answer_title") or "Untitled").strip()
        body = (
            str(metadata.get("answer_body") or getattr(document, "page_content", "") or "")
            .replace(
                "\n",
                " ",
            )
            .strip()
        )
        url = str(metadata.get("url") or metadata.get("answer_url") or "").strip()
        sections.append("{}. {} (score: {:.3f})".format(index, title, score))
        if body:
            sections.append("   " + body)
        if url:
            sections.append("   " + url)

    return "\n".join(sections).strip()


def build_knowledgebase_middleware(query_model: BaseChatModel):
    """Create middleware that injects KB context before the model is called."""

    @before_agent
    async def knowledgebase_middleware(state: dict[str, Any], runtime: Any) -> dict[str, Any] | None:
        if getattr(runtime.context, "knowledgebase_context", None):
            return None

        try:
            context = await _build_kb_context(runtime, query_model, state.get("messages", []))
            runtime.context.knowledgebase_context = context
            return {"messages": [SystemMessage(content=context)]}
        except Exception:
            logger.error("Failed to build knowledge-base context.", exc_info=True)
            runtime.context.knowledgebase_context = KB_CONTEXT_EMPTY
            return {"messages": [SystemMessage(content=KB_CONTEXT_EMPTY)]}

    return knowledgebase_middleware


@observe(as_type="span")
async def _format_answer(
    chat_model: BaseChatModel,
    structured_response: AnswerCandidate,
    langfuse_client: Any | None,
    format_prompt: str,
    format_langfuse_prompt: Any,
    session_id: str | None = None,
) -> AnswerCandidate:
    """Format the answer of the agent."""
    prompt_template = ChatPromptTemplate(
        messages=[
            ("system", format_prompt),
            ("human", "{answer_payload}"),
        ]
    )
    if format_langfuse_prompt is not None:
        prompt_template.metadata = {"langfuse_prompt": format_langfuse_prompt}

    config: RunnableConfig = (
        langfuse_client.build_config(session_id=session_id)
        if langfuse_client is not None
        else RunnableConfig()
    )
    structured_model = chat_model.with_structured_output(AnswerCandidate)
    chain = prompt_template | structured_model
    with propagate_attributes(session_id=session_id):
        result = await chain.ainvoke(
            {"answer_payload": structured_response.model_dump_json(indent=2)},
            config=config,
        )

    return result if isinstance(result, AnswerCandidate) else AnswerCandidate.model_validate(result)
