api:
  host: 0.0.0.0
  port: 8081
  auth_token:
  max_input_length: 10000

guardrails:
  confidence_threshold: 0.7
  huggingface_cache_dir: /app/huggingface_cache
  offline_mode: true
  max_concurrency: 4
  default_model: default
  models:
    default:
      hf_model_name: fastino/gliguard-LLMGuardrails-300M
