[project]
name = "zammad-ai"
license = { file = "LICENSE" }
version = "0.1.0"
description = "GenAI-powered agent for Zammad"
readme = "README.md"
requires-python = "==3.13.7"
authors = [
    { name = "Fabian Reinold", email = "fabian.reinold@muenchen.de" },
    { name = "Lena Barth", email = "lena.barth@muenchen.de" },
    { name = "Paul Ilitz", email = "paul.ilitz@muenchen.de" },
]
maintainers = [
    { name = "Fabian Reinold", email = "fabian.reinold@muenchen.de" },
]

dependencies = [
    "faststream[cli,kafka]==0.5.48",
    "pydantic-settings==2.10.1",
    "python-dotenv==1.1.1",
    "truststore==0.10.4",
]

[dependency-groups]
dev = [
    "pre-commit==4.3.0",
    "ruff==0.13.1",
    "ipykernel==6.30.1",
    "jupyter==1.1.1",
]

[tool.uv]
add-bounds = "exact"
